eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://172.17.0.2:8761/eureka
  instance:
    prefer-ip-address: true
    hostname: 172.17.0.2
